name: WordPress Auto Post

on:
  schedule:
    - cron: '0 * * * *'  # 매시간 0분마다 실행
  workflow_dispatch:      # 수동 실행 허용

permissions:
  contents: write

jobs:
  post_to_wordpress:
    runs-on: ubuntu-latest

    steps:
    - name: 저장소 체크아웃
      uses: actions/checkout@v3

    - name: Python 설정
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.1'  # Python 버전 확인 (필요 시 수정)

    - name: 종속성 설치
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # requirements.txt 파일 확인

    - name: 환경 변수 로드 및 확인
      env:
        WORDPRESS_URL: ${{ secrets.WORDPRESS_URL }}
        WORDPRESS_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
        WORDPRESS_PASSWORD: ${{ secrets.WORDPRESS_PASSWORD }}
      run: |
        echo "WORDPRESS_URL=${WORDPRESS_URL}"
        echo "WORDPRESS_USERNAME=${WORDPRESS_USERNAME}"
        echo "WORDPRESS_PASSWORD=${WORDPRESS_PASSWORD}"

    - name: 워드프레스 자동 포스팅 실행
      env:
        WORDPRESS_URL: ${{ secrets.WORDPRESS_URL }}
        WORDPRESS_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
        WORDPRESS_PASSWORD: ${{ secrets.WORDPRESS_PASSWORD }}
      run: python blog_auto_post.py  # blog_auto_post.py 파일 확인
